function batch

%%      GET FIGURES FOR CCM: CCM_SINGLE_NEURON, CCM_DDM_LIKE, AND CCM_NEURON_STOP_VS_GO

% dataPath = 'Broca_sessions.mat';
% load(dataPath)
% nSession = length(sessions.ccm.stop);

subjectID = 'Broca';
taskID = 'ccm';
dataIncludeArray = {'spike'};

sessionList = find_sessions_data(subjectID, taskID, dataIncludeArray);



%%
for i = 1 : length(sessionList)
   iSessionID = sessionList{i}
   [data, options] = ccm_session_data(subjectID, iSessionID,'neuron', 'normalize', false, 'filterData', true,'collapseSignal', false, 'printPlot', true);
   options.collapseSignal = true;
   ccm_session_data_plot(data, 'neuron', options);
   ccm_neuron_stop_vs_go(subjectID, iSessionID, 'collapseSignal', 1, 'printPlot', 1);
   ddmLike = ccm_ddm_like(subjectID, iSessionID, 'printPlot', 1);
end


%%
sessionArray = ...
   {'bp076n01', ...
   'bp077n01', ...
   'bp080n01', ...
   'bp081n01', ...
   'bp082n02', ...
   'bp084n02', ...
   'bp086n01', ...
   'bp087n02', ...
   'bp088n02', ...
   'bp089n02', ...
   'bp090n02', ...
   'bp091n02-pm', ...
   'bp092n02', ...
   'bp093n02', ...
   'bp095n04', ...
   'bp096n02', ...
   'bp097n03', ...
   'bp099n02-pm', ...
   'bp100n01', ...
   'bp101n01', ...
   'bp103n01', ...
   'bp104n01', ...
   'bp106n01', ...
   'bp107n01', ...
   'bp109n01', ...
   'bp110n01-pm', ...
   'bp111n02-pm', ...
   'bp112n02-pm', ...
   'bp113n01', ...
   'bp114n01', ...
   'bp115n02', ...
   'bp116n02-pm', ...
   'bp117n01', ...
   'bp118n01', ...
   'bp119n02-pm', ...
   'bp120n02-pm', ...
   'bp121n02-pm', ...
   'bp121n04', ...
   'bp122n02', ...
   'bp123n01', ...
   'bp124n02', ...
   'bp124n04', ...
   'bp126n02-pm', ...
   'bp127n02', ...
   'bp128n02', ...
   'bp129n02-pm', ...
   'bp130n04', ...
   'bp131n02', ...
   'bp132n02-pm'};


for i = length(sessionArray)
   iSessionID = sessionArray{i}
   
   [td, SessionData, ExtraVar] = load_data('broca', iSessionID);
   disp([ExtraVar.pSignalArray, unique(sum(td.checkerArray,2))])
   pause
end


%%
sessionArray = ...
   {'andy_fef_086', ...
   'andy_fef_096', ...
   'andy_fef_196', ...
   'andy_fef_215', ...
   'andy_fef_218', ...
   'andy_fef_219', ...
   'andy_fef_220', ...
   'andy_fef_221', ...
   'andy_fef_226', ...
   'andy_fef_228', ...
   'andy_fef_234', ...
   'andy_fef_240'};

subjectID = 'andy';
ssrt = nan(length(sessionArray), 1);
ssdArray  = [];
nTrial = nan(length(sessionArray), 1);
for i = 3 : length(sessionArray)
   sessionArray{i}
   D(i).data = cmd_inhibition(subjectID, sessionArray{i});
   
   ssrt(i) = D(i).data.ssrt.integrationWeighted;
   ssdArray = [ssdArray; D(i).data.ssdArray];
   D(i).data.nTrial
   nTrial(i) = D(i).data.nTrial;
   
   pause
   data = cmd_session_data(subjectID, sessionArray{i});
   pause
   cmd_neuron_stop_vs_go(subjectID, sessionArray{i});
   pause
end
%%
sessionArray = ...
   {'andy_fef_084', ...
   'andy_fef_096', ...
   'andy_fef_154', ...
   'andy_fef_196', ...
   'andy_fef_215', ...
   'andy_fef_218', ...
   'andy_fef_219', ...
   'andy_fef_220', ...
   'andy_fef_226', ...
   'andy_fef_228', ...
   'andy_fef_234', ...
   'andy_fef_240'};

subjectID = 'andy';
ssrt = nan(length(sessionArray), 1);
ssdArray  = [];
nTrial = nan(length(sessionArray), 1);
for i = 1 : length(sessionArray)
   D(i).data = cmd_inhibition(subjectID, sessionArray{i}, 'plotFlag', false)
   
   ssrt(i) = D(i).data.ssrt.integrationWeighted
   ssdArray = [ssdArray; D(i).data.ssdArray]
   nTrial(i) = D(i).data.nTrial
end
%%
sessionArray = ...
   {'chase_fef_375', ...
   'chase_fef_387', ...
   'chase_fef_389', ...
   'chase_fef_395', ...
   'chase_fef_413'};

subjectID = 'chase';
ssrt = nan(length(sessionArray), 1);
ssdArray  = [];
nTrial = nan(length(sessionArray), 1);
for i = 1 : length(sessionArray)
   D(i).data = cmd_inhibition(subjectID, sessionArray{i})
%    D(i).data = cmd_inhibition(subjectID, sessionArray{i}, 'plotFlag', false)
   pause
   ssrt(i) = D(i).data.ssrt.integrationWeighted
   ssdArray = [ssdArray; D(i).data.ssdArray]
   nTrial(i) = D(i).data.nTrial
end
